### ISSUE TITLE
Steadfast Ranger Update

### ISSUE THREAD

**Issue by jackbauer999** [zeobviouslyfakeacc/DisableBreathEffect#1]
The update yesterday seems to block this mod, maybe all mods?

**Comment by zeobviouslyfakeacc** [comment]
I completely missed this issue! Sorry about that!

And yeah, v1.48 broke all mods and made modding more or less impossible. Fortunately, this change was reverted in v1.48.1 and newer, so (at least for some time), a new version of the mod loader works again.

So if you install [version 1.5](https://github.com/zeobviouslyfakeacc/ModLoaderInstaller/releases/tag/v1.5) of the mod loader, the current version of DisableBreathEffect should work again 😄
